#6 スタート、リザルト画面を追加
OUCC/oucc-music-game pull request #13
Opened 2023-03-20 13:10 UTC by watanabe4869

スタート、リザルト画面に必要な機能を追加しました。

2023-03-20 13:57 UTC, miyaji255 requested changes
結構多いですがお願いします。

以下は全体的に修正してほしい点です。
- 不要なusingの削除
- 不要な`Start` `Update` メソッドの削除
- privateアクセシビリティの明示
- ローカル変数は小文字からフィールドは大文字から始める
- `rankText`などアセット名は基本大文字から始めてください。(例: `start scene`, `resultManager`)
- エディタでのフォーマット

2023-03-20 13:57 UTC, miyaji255 commented on Assets/Scripts/SpeedSelect.cs
> +        public TextMeshProUGUI speedText;
シリアライズ不要でしたら`NonSerialized`をつけるかprivateにしておいてください

2023-03-20 13:57 UTC, miyaji255 commented on Assets/Scripts/Manager/resultText.cs
> +    public class resultText : MonoBehaviour
クラスは大文字から始めてください

2023-03-20 13:57 UTC, miyaji255 commented on Assets/Scripts/Manager/resultText.cs
> +        public TextMeshProUGUI scoreText , comboText , perfectText , greatText , goodText , badText , missText , rankText;
publicフィールドは大文字から始めてください。また、特筆するべき事情がない限りpublicフィールドはバラバラに宣言してできるだけコメントをつけるようにしてください。

今回は外から使うことも特にないと思うのでprivateフィールドにして`SerializeField`にすれば良いと思います。

2023-03-20 13:57 UTC, miyaji255 commented on Assets/Scripts/Manager/resultText.cs
> +        ScoreManager scoreManager = new ScoreManager();
`ScoreManager`はインスタンス化せずに`ScoreManager.Instance`を使用してください

2023-03-20 13:57 UTC, miyaji255 commented on Assets/Scripts/Manager/resultText.cs
> +        }
`Update`ではなく`Start`でいいように思われます。`Update`に書いた理由はありますか？

2023-03-20 13:57 UTC, miyaji255 commented on Assets/Scripts/Manager/resultText.cs
> +            int currentScore = scoreManager.CurrentScore;
`var`を使うほうが見やすいと思うのですがなぜ使わないのでしょうか？

2023-03-20 13:57 UTC, miyaji255 commented on Assets/Scripts/Manager/resultText.cs
> +            var score_rate = currentScore/totalScore;
`int/int`は切り捨てられます。どちらかを`float`にキャストしてください

2023-03-20 13:57 UTC, miyaji255 commented on Assets/Scripts/scoreText.cs
> +    public class scoreText : MonoBehaviour
これは使用していますか？

2023-03-20 13:57 UTC, miyaji255 commented on Assets/Scripts/Manager/resultText.cs
> +            missText.text = "miss : " + Counts.Item5.ToString();
明示的に名前をしているはずなのでそちらを使用してください

2023-03-21 05:04 UTC, watanabe4869 commented
修正しました。

2023-03-21 06:31 UTC, miyaji255 commented
C#系はsnake_caseではなくPascalCaseなのでそちらに修正してください。あと修正できていないポイントがあります。

2023-03-21 10:54 UTC, watanabeRRR commented
修正が抜けている場所があれば言ってください。

2023-03-21 10:56 UTC, miyaji255 commented
ファイル名やアセット名をPascalCaseに統一してほしいです。あと、imageフォルダがないと怒られています。imageフォルダに何も入れない予定なら削除してください

2023-03-21 11:41 UTC, watanabeRRR commented
ファイルの名前を変更したらリモートの方にだけ変更前のファイルが残っているんですけど、何でか分かりますか？

2023-03-21 11:44 UTC, miyaji255 commented
正しく`add`できてないとかですかね？Unityで名前変更しましたか？Unityで変更しないとmetaファイルも一緒に改変されません。

2023-03-21 11:46 UTC, watanabe4869 commented
Unityで変更しました。

2023-03-21 11:47 UTC, miyaji255 commented
じゃあ保存できてないとかですかね？もう一度コミットしようとしてみてもらってもいいですか？

2023-03-21 12:01 UTC, watanabe4869 commented
VScodeの方でコミットしたら出来ました。

2023-03-21 12:02 UTC, miyaji255 approved these changes
ありがとうございました

2023-03-21 12:03 UTC, merged