Feat/#5 main scean
OUCC/oucc-music-game pull request #8
Opened 2023-03-17 12:17 UTC by frog3141

スコアとコンボ数を出すUIを準備（置いただけだけれども）

2023-03-17 12:24 UTC, miyaji255 requested changes
Note CheckerにObjectをアタッチしていないためぬるぽになっています

2023-03-17 12:32 UTC, miyaji255 requested changes
画面サイズを変えるとUIが崩れます。これを使って起点を調整してください
![image](https://user-images.githubusercontent.com/84168445/225905369-d2d943c1-9114-490f-8912-3fee34c1e625.png)

2023-03-17 12:40 UTC, miyaji255 requested changes
ノーツを生成するポイントはGameManagerで計算するので`NoteMakePoint`はチェックラインにしておいてください。また、アクセシビリティ(publicとかprivate)は必ず書いてください。シリアライズしなくていいもの(`NoteLanePoint`とか)には`NonSerialized`属性をつけといてください。属性は以下のようにひとつ上の行につけてください。

```cs
[SerializeField]
private List<GameObject> _noteLane;
```

2023-03-17 12:48 UTC, miyaji255 requested changes
ノーツを非表示にするのは`GameObject`のDestroy操作が遅いためです。`gameObject.SetActive(false)`も遅いので早い操作に変更してください。

2023-03-17 12:48 UTC, miyaji255 commented on Assets/Scripts/NoteContoroler.cs
>              }
時間ではなくチェックラインを超えて少ししたらミス判定を出すようにしてください。あとthisを使わなくていい時は使わないようにしてください

2023-03-17 15:18 UTC, frog3141 commented
指摘を受けた部分を修正しました。
ノーツの非表示処理はgameObject.SetActive(false)の代わりにMeshRenderer.enable=falseで実装しましたが問題ないでしょうか？

2023-03-18 08:01 UTC, miyaji255 commented
> 指摘を受けた部分を修正しました。 ノーツの非表示処理はgameObject.SetActive(false)の代わりにMeshRenderer.enable=falseで実装しましたが問題ないでしょうか？
適当に別のところへ配置するのかと思っていました。速度的に問題ないなら大丈夫です。

2023-03-18 08:12 UTC, miyaji255 requested changes
追加でごめんなさい

2023-03-18 08:12 UTC, miyaji255 commented on Assets/Scripts/NoteContoroler.cs
> +            transform.position += Vector3.back * NoteVelocity;
`Vector3.back * NoteVelocity`だとUpdateが走るスピードに依存しませんか？`Vector3.back * NoteVelocity * Time.deltaTime`の方がいいと思います。

2023-03-18 08:12 UTC, miyaji255 commented on Assets/Scripts/NoteContoroler.cs
>          }
`Start`などのUnityの関数は中身がなくても実行されて負荷になるので、必要ないなら消しましょう。

2023-03-18 08:12 UTC, miyaji255 commented on Assets/Scripts/NoteContoroler.cs
>          /// </summary>
フィールドや関数のコメントはこのように書くことでIDEに説明が表示されます。例えば`NoteVelocity`は下のように書くことができます。また、他の関数やフィールドとの間は一行開けたほうがきれいだと思います。
```cs
/// <summary>
/// ノーツの移動速度 
/// </summary>
[NonSerialized]
public float NoteVelocity;
```

2023-03-21 06:22 UTC, frog3141 commented
すいません完全に見逃してました。
指摘部分を修正し、publicの変数、関数には一通りコメントを追記しました。

2023-03-21 06:48 UTC, miyaji255 approved these changes
大丈夫です

2023-03-21 06:48 UTC, merged